"""Lookup known default credentials for a vendor or product.

Pure data lookup. No network. Returns vendor/product → list of credential
pairs sourced from public references (vendor docs, SecLists, CISA KEV
advisories, CVE notes).

For authorized testing only. Atomic: query in → list out, no probing.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

CREDS: dict[str, list[dict[str, str]]] = {
    "router:cisco": [
        {"username": "cisco", "password": "cisco", "note": "default on many IOS images"},
        {"username": "admin", "password": "admin", "note": "common SMB"},
    ],
    "router:mikrotik": [{"username": "admin", "password": "", "note": "RouterOS factory default"}],
    "router:tplink": [{"username": "admin", "password": "admin"}],
    "router:dlink": [{"username": "admin", "password": "admin"}, {"username": "admin", "password": ""}],
    "router:netgear": [{"username": "admin", "password": "password"}],
    "router:huawei": [{"username": "admin", "password": "admin"}, {"username": "root", "password": "admin"}],
    "switch:cisco": [{"username": "cisco", "password": "cisco"}],
    "firewall:fortinet": [{"username": "admin", "password": "", "note": "FortiGate factory default"}],
    "firewall:paloalto": [{"username": "admin", "password": "admin"}],
    "ipmi:supermicro": [{"username": "ADMIN", "password": "ADMIN"}],
    "ipmi:dell": [{"username": "root", "password": "calvin"}],
    "ipmi:hp": [{"username": "Administrator", "password": "<unique-per-device>", "note": "iLO label on device"}],
    "db:mysql": [{"username": "root", "password": ""}],
    "db:postgres": [{"username": "postgres", "password": "postgres"}],
    "db:mongodb": [{"username": "", "password": "", "note": "anonymous bind on old defaults"}],
    "db:mssql": [{"username": "sa", "password": "sa"}, {"username": "sa", "password": ""}],
    "db:redis": [{"username": "", "password": "", "note": "no auth by default pre-6.0"}],
    "db:elasticsearch": [{"username": "elastic", "password": "changeme", "note": "pre-8.x default"}],
    "db:oracle": [
        {"username": "sys", "password": "change_on_install"},
        {"username": "system", "password": "manager"},
        {"username": "scott", "password": "tiger"},
    ],
    "app:jenkins": [{"username": "admin", "password": "<auto-generated, /var/jenkins_home/secrets/initialAdminPassword>"}],
    "app:tomcat": [
        {"username": "tomcat", "password": "tomcat", "note": "manager-gui role"},
        {"username": "admin", "password": "admin"},
        {"username": "manager", "password": "manager"},
    ],
    "app:jboss": [{"username": "admin", "password": "admin"}],
    "app:weblogic": [{"username": "weblogic", "password": "weblogic"}, {"username": "weblogic", "password": "welcome1"}],
    "app:websphere": [{"username": "admin", "password": "admin"}],
    "app:phpmyadmin": [{"username": "root", "password": ""}],
    "app:grafana": [{"username": "admin", "password": "admin"}],
    "app:gitlab": [{"username": "root", "password": "5iveL!fe", "note": "first-run default on old installs"}],
    "app:jira": [{"username": "admin", "password": "admin"}],
    "app:confluence": [{"username": "admin", "password": "admin"}],
    "app:sonarqube": [{"username": "admin", "password": "admin"}],
    "app:nexus": [{"username": "admin", "password": "admin123"}],
    "app:rundeck": [{"username": "admin", "password": "admin"}],
    "app:wordpress": [{"username": "admin", "password": "admin"}],
    "app:joomla": [{"username": "admin", "password": "admin"}],
    "app:drupal": [{"username": "admin", "password": "admin"}],
    "app:zabbix": [{"username": "Admin", "password": "zabbix"}],
    "app:nagios": [{"username": "nagiosadmin", "password": "nagiosadmin"}],
    "app:prtg": [{"username": "prtgadmin", "password": "prtgadmin"}],
    "app:splunk": [{"username": "admin", "password": "changeme"}],
    "app:kibana": [{"username": "elastic", "password": "changeme"}],
    "app:rabbitmq": [{"username": "guest", "password": "guest"}],
    "app:airflow": [{"username": "airflow", "password": "airflow"}],
    "service:ftp:anonymous": [{"username": "anonymous", "password": "anonymous"}, {"username": "anonymous", "password": ""}],
    "service:ssh:raspbian": [{"username": "pi", "password": "raspberry"}],
    "service:vnc": [{"username": "", "password": "<blank — old defaults often passwordless>"}],
    "iot:hikvision": [{"username": "admin", "password": "12345"}],
    "iot:dahua": [{"username": "admin", "password": "admin"}],
    "iot:axis": [{"username": "root", "password": "pass"}],
}

ALIASES: dict[str, str] = {
    "fortigate": "firewall:fortinet",
    "palo": "firewall:paloalto",
    "panos": "firewall:paloalto",
    "mssql-server": "db:mssql",
    "sql-server": "db:mssql",
    "psql": "db:postgres",
    "mongo": "db:mongodb",
    "es": "db:elasticsearch",
    "elastic": "db:elasticsearch",
    "wp": "app:wordpress",
    "phpmyadmin": "app:phpmyadmin",
    "pma": "app:phpmyadmin",
    "ilo": "ipmi:hp",
    "idrac": "ipmi:dell",
    "drac": "ipmi:dell",
}


class CredEntry(BaseModel):
    username: str
    password: str
    note: str | None = None


class LookupReport(BaseModel):
    query: str
    matched_keys: list[str] = Field(default_factory=list)
    credentials: list[CredEntry] = Field(default_factory=list)
    note: str = (
        "For authorized testing only. Defaults change across firmware versions; "
        "always confirm against the specific build/release in scope."
    )


def default_creds_lookup(query: str) -> dict:
    """Return known default credentials for a vendor / product / service.

    Accepts a short product name (`cisco`, `tomcat`, `idrac`, `mongo`),
    a full key (`router:cisco`, `db:mongodb`), or a substring match.
    Returns every credential pair across all matching keys.

    Pure data lookup — no network, no scanning.

    Args:
        query: vendor / product / service identifier (case-insensitive).

    Returns:
        LookupReport with `matched_keys` and `credentials`.
    """
    if not isinstance(query, str) or not query.strip():
        return {"error": "query must be a non-empty string"}

    q = query.strip().lower()
    if q in ALIASES:
        q = ALIASES[q]

    matched: list[str] = []
    if q in CREDS:
        matched = [q]
    else:
        for key in CREDS:
            if q in key or q in key.split(":")[-1]:
                matched.append(key)
        for alias, target in ALIASES.items():
            if q in alias and target not in matched:
                matched.append(target)

    creds: list[CredEntry] = []
    for k in matched:
        for entry in CREDS.get(k, []):
            creds.append(CredEntry(**entry))

    return LookupReport(query=query, matched_keys=matched, credentials=creds).model_dump()
